version: '3.8'

services:
  api-dev:
    container_name: library-api-dev
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ./api/src/config/.env
    volumes:
      - ./api/src:/app/src
    networks:
      - stanleyclaudius

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - stanleyclaudius

volumes:
  mongodb:

networks:
  stanleyclaudius: